### ISSUE TITLE
Unable to Start App

### ISSUE THREAD

**Issue by swapnil-gawali** [willsoto/nestjs-objection#1000]
Following is my `database.module.ts` file :

```
import { Module } from '@nestjs/common';
import { ObjectionModule } from '@willsoto/nestjs-objection';
import { knexSnakeCaseMappers } from "objection";
import { UserModel } from './model/user.model';

@Module({
    imports: [
        ObjectionModule.register({
            // You can specify a custom BaseModel
            // If none is provided, the default Model will be used
            // https://vincit.github.io/objection.js/#models
            config: {
                client: 'postgresql',
                connection: {
                    host: '127.0.0.1',
                    user: 'postgres',
                    password: 'swapnil',
                    database: 'test'
                },
                pool: {
                    min: 2,
                    max: 10
                },
                ...knexSnakeCaseMappers()
            }
        }),

        //Register your objection models so it can be provided when needed.
        ObjectionModule.forFeature([UserModel]),
    ],
    exports: [ObjectionModule],
})
export class DatabaseModule {
}

```

Model Class : 

```
import { Model } from 'objection';

export class UserModel extends Model {
    static tableName = 'user';

    id: number;
    name: string;
}
```

Getting this error while running the app:

```
node_modules/knex/types/index.d.ts:1116:16 - error TS1110: Type expected.

1116       column1: `${TTable1}.${TKey1}`,
~~~

    node_modules/knex/types/index.d.ts:1117:14 - error TS1005: ';' expected.

1117       column2: `${TTable2}.${TKey2}`
~

    node_modules/knex/types/index.d.ts:1118:5 - error TS1128: Declaration or statement expected.

1118     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:1118:6 - error TS1128: Declaration or statement expected.

1118     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:1118:40 - error TS1005: '(' expected.

1118     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:1120:33 - error TS1005: '?' expected.

1120       TTable1 extends TableNames,
~

    node_modules/knex/types/index.d.ts:1121:15 - error TS1005: ';' expected.

1121       TTable2 extends TableNames,
~~~~~~~

    node_modules/knex/types/index.d.ts:1122:13 - error TS1005: ';' expected.

1122       TKey1 extends StrKey<ResolveTableType<TableType<TTable1>>> & StrKey<TRecord1>,
~~~~~~~

    node_modules/knex/types/index.d.ts:1122:66 - error TS1005: '(' expected.

1122       TKey1 extends StrKey<ResolveTableType<TableType<TTable1>>> & StrKey<TRecord1>,
~

    node_modules/knex/types/index.d.ts:1122:84 - error TS1109: Expression expected.

1122       TKey1 extends StrKey<ResolveTableType<TableType<TTable1>>> & StrKey<TRecord1>,
~

    node_modules/knex/types/index.d.ts:1123:13 - error TS1005: ',' expected.

1123       TKey2 extends StrKey<ResolveTableType<TableType<TTable2>>>,
~~~~~~~

    node_modules/knex/types/index.d.ts:1123:65 - error TS1109: Expression expected.

1123       TKey2 extends StrKey<ResolveTableType<TableType<TTable2>>>,
~

    node_modules/knex/types/index.d.ts:1124:43 - error TS1109: Expression expected.

1124       TRecord1 = ResolveTableType<TRecord>,
~

    node_modules/knex/types/index.d.ts:1125:65 - error TS1109: Expression expected.

1125       TRecord2 = TRecord1 & ResolveTableType<TableType<TTable2>>,
~

    node_modules/knex/types/index.d.ts:1127:5 - error TS1109: Expression expected.

1127     >(
    ~

        node_modules/knex/types/index.d.ts:1128:16 - error TS1005: ')' expected.

1128       tableName: TTable2,
~

    node_modules/knex/types/index.d.ts:1129:14 - error TS1005: ',' expected.

1129       column1: `${TTable2}.${TKey2}`,
~

    node_modules/knex/types/index.d.ts:1130:14 - error TS1005: ',' expected.

1130       column2: `${TTable1}.${TKey1}`
~

    node_modules/knex/types/index.d.ts:1131:6 - error TS1005: ';' expected.

1131     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:1131:40 - error TS1005: '(' expected.

1131     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:1133:36 - error TS1005: '?' expected.

1133       TJoinTargetRecord extends {} = any,
~

    node_modules/knex/types/index.d.ts:1134:16 - error TS1005: ';' expected.

1134       TRecord2 extends {} = TRecord & TJoinTargetRecord,
~~~~~~~

    node_modules/knex/types/index.d.ts:1134:27 - error TS1128: Declaration or statement expected.

1134       TRecord2 extends {} = TRecord & TJoinTargetRecord,
~

    node_modules/knex/types/index.d.ts:1136:5 - error TS1109: Expression expected.

1136     >(
    ~

        node_modules/knex/types/index.d.ts:1137:16 - error TS1005: ')' expected.

1137       tableName: TableDescriptor | AliasDict | QueryCallback,
~

    node_modules/knex/types/index.d.ts:1138:14 - error TS1005: ';' expected.

1138       column1: string,
~

    node_modules/knex/types/index.d.ts:1139:14 - error TS1005: ';' expected.

1139       column2: string
~

    node_modules/knex/types/index.d.ts:1140:5 - error TS1128: Declaration or statement expected.

1140     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:1140:6 - error TS1128: Declaration or statement expected.

1140     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:1140:40 - error TS1005: '(' expected.

1140     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:1142:36 - error TS1005: '?' expected.

1142       TJoinTargetRecord extends {} = any,
~

    node_modules/knex/types/index.d.ts:1143:16 - error TS1005: ';' expected.

1143       TRecord2 extends {} = TRecord & TJoinTargetRecord,
~~~~~~~

    node_modules/knex/types/index.d.ts:1143:27 - error TS1128: Declaration or statement expected.

1143       TRecord2 extends {} = TRecord & TJoinTargetRecord,
~

    node_modules/knex/types/index.d.ts:1145:5 - error TS1109: Expression expected.

1145     >(
    ~

        node_modules/knex/types/index.d.ts:1146:16 - error TS1005: ')' expected.

1146       tableName: TableDescriptor | AliasDict | QueryCallback,
~

    node_modules/knex/types/index.d.ts:1147:14 - error TS1005: ';' expected.

1147       column1: string,
~

    node_modules/knex/types/index.d.ts:1148:10 - error TS1005: ';' expected.

1148       raw: Raw
~

    node_modules/knex/types/index.d.ts:1149:5 - error TS1128: Declaration or statement expected.

1149     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:1149:6 - error TS1128: Declaration or statement expected.

1149     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:1149:40 - error TS1005: '(' expected.

1149     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:1151:33 - error TS1005: '?' expected.

1151       TTable1 extends TableNames,
~

    node_modules/knex/types/index.d.ts:1152:15 - error TS1005: ';' expected.

1152       TTable2 extends TableNames,
~~~~~~~

    node_modules/knex/types/index.d.ts:1153:13 - error TS1005: ';' expected.

1153       TKey1 extends StrKey<ResolveTableType<TableType<TTable1>>> & StrKey<TRecord1>,
~~~~~~~

    node_modules/knex/types/index.d.ts:1153:66 - error TS1005: '(' expected.

1153       TKey1 extends StrKey<ResolveTableType<TableType<TTable1>>> & StrKey<TRecord1>,
~

    node_modules/knex/types/index.d.ts:1153:84 - error TS1109: Expression expected.

1153       TKey1 extends StrKey<ResolveTableType<TableType<TTable1>>> & StrKey<TRecord1>,
~

    node_modules/knex/types/index.d.ts:1154:13 - error TS1005: ',' expected.

1154       TKey2 extends StrKey<ResolveTableType<TableType<TTable2>>>,
~~~~~~~

    node_modules/knex/types/index.d.ts:1154:65 - error TS1109: Expression expected.

1154       TKey2 extends StrKey<ResolveTableType<TableType<TTable2>>>,
~

    node_modules/knex/types/index.d.ts:1155:43 - error TS1109: Expression expected.

1155       TRecord1 = ResolveTableType<TRecord>,
~

    node_modules/knex/types/index.d.ts:1156:65 - error TS1109: Expression expected.

1156       TRecord2 = TRecord1 & ResolveTableType<TableType<TTable2>>,
~

    node_modules/knex/types/index.d.ts:1158:5 - error TS1109: Expression expected.

1158     >(
    ~

        node_modules/knex/types/index.d.ts:1159:16 - error TS1005: ')' expected.

1159       tableName: TTable2,
~

    node_modules/knex/types/index.d.ts:1160:14 - error TS1005: ',' expected.

1160       column1: `${TTable1}.${TKey1}`,
~

    node_modules/knex/types/index.d.ts:1161:15 - error TS1005: ',' expected.

1161       operator: string,
~

    node_modules/knex/types/index.d.ts:1162:14 - error TS1005: ',' expected.

1162       column2: `${TTable2}.${TKey2}`
~

    node_modules/knex/types/index.d.ts:1163:6 - error TS1005: ';' expected.

1163     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:1163:40 - error TS1005: '(' expected.

1163     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:1165:33 - error TS1005: '?' expected.

1165       TTable1 extends TableNames,
~

    node_modules/knex/types/index.d.ts:1166:15 - error TS1005: ';' expected.

1166       TTable2 extends TableNames,
~~~~~~~

    node_modules/knex/types/index.d.ts:1167:13 - error TS1005: ';' expected.

1167       TKey1 extends StrKey<ResolveTableType<TableType<TTable1>>> & StrKey<TRecord1>,
~~~~~~~

    node_modules/knex/types/index.d.ts:1167:66 - error TS1005: '(' expected.

1167       TKey1 extends StrKey<ResolveTableType<TableType<TTable1>>> & StrKey<TRecord1>,
~

    node_modules/knex/types/index.d.ts:1167:84 - error TS1109: Expression expected.

1167       TKey1 extends StrKey<ResolveTableType<TableType<TTable1>>> & StrKey<TRecord1>,
~

    node_modules/knex/types/index.d.ts:1168:13 - error TS1005: ',' expected.

1168       TKey2 extends StrKey<ResolveTableType<TableType<TTable2>>>,
~~~~~~~

    node_modules/knex/types/index.d.ts:1168:65 - error TS1109: Expression expected.

1168       TKey2 extends StrKey<ResolveTableType<TableType<TTable2>>>,
~

    node_modules/knex/types/index.d.ts:1169:43 - error TS1109: Expression expected.

1169       TRecord1 = ResolveTableType<TRecord>,
~

    node_modules/knex/types/index.d.ts:1170:65 - error TS1109: Expression expected.

1170       TRecord2 = TRecord1 & ResolveTableType<TableType<TTable2>>,
~

    node_modules/knex/types/index.d.ts:1172:5 - error TS1109: Expression expected.

1172     >(
    ~

        node_modules/knex/types/index.d.ts:1173:16 - error TS1005: ')' expected.

1173       tableName: TTable2,
~

    node_modules/knex/types/index.d.ts:1174:14 - error TS1005: ',' expected.

1174       column1: `${TTable2}.${TKey2}`,
~

    node_modules/knex/types/index.d.ts:1175:15 - error TS1005: ',' expected.

1175       operator: string,
~

    node_modules/knex/types/index.d.ts:1176:14 - error TS1005: ',' expected.

1176       column2: `${TTable1}.${TKey1}`,
~

    node_modules/knex/types/index.d.ts:1177:6 - error TS1005: ';' expected.

1177     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:1177:40 - error TS1005: '(' expected.

1177     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:1179:36 - error TS1005: '?' expected.

1179       TJoinTargetRecord extends {} = any,
~

    node_modules/knex/types/index.d.ts:1180:16 - error TS1005: ';' expected.

1180       TRecord2 extends {} = TRecord & TJoinTargetRecord,
~~~~~~~

    node_modules/knex/types/index.d.ts:1180:27 - error TS1128: Declaration or statement expected.

1180       TRecord2 extends {} = TRecord & TJoinTargetRecord,
~

    node_modules/knex/types/index.d.ts:1182:5 - error TS1109: Expression expected.

1182     >(
    ~

        node_modules/knex/types/index.d.ts:1183:16 - error TS1005: ')' expected.

1183       tableName: TableDescriptor | AliasDict | QueryCallback,
~

    node_modules/knex/types/index.d.ts:1184:14 - error TS1005: ';' expected.

1184       column1: string,
~

    node_modules/knex/types/index.d.ts:1185:15 - error TS1005: ';' expected.

1185       operator: string,
~

    node_modules/knex/types/index.d.ts:1186:14 - error TS1005: ';' expected.

1186       column2: string
~

    node_modules/knex/types/index.d.ts:1187:5 - error TS1128: Declaration or statement expected.

1187     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:1187:6 - error TS1128: Declaration or statement expected.

1187     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:1187:40 - error TS1005: '(' expected.

1187     ): QueryBuilder<TRecord2, TResult2>;
~

    node_modules/knex/types/index.d.ts:2423:1 - error TS1128: Declaration or statement expected.

2423 }
~

    [7:54:04 pm] Found 84 errors. Watching for file changes.


```

**Comment by willsoto** [comment]
Looking at the stack trace, every error is in `knex/types/index.d.ts`, so why do you believe this package is the problem?

**Comment by swapnil-gawali** [comment]
@willsoto I had older version of typescript installed, later upgrading to the latest TS version, i am getting following error:

```
node_modules/@willsoto/nestjs-objection/typings/interfaces.d.ts:12:13 - error TS2503: Cannot find namespace 'Knex'.

12     config: Knex.Config;
               ~~~~

node_modules/@willsoto/nestjs-objection/typings/interfaces.d.ts:28:34 - error TS2749: 'Knex' refers to a value, but is being used as a type here. Did you mean 'typeof Knex'?

28 export declare type Connection = Knex;
                                    ~~~~

node_modules/objection/typings/objection/index.d.ts:120:32 - error TS2694: Namespace '"C:/Users/swapn/IdeaProjects/nest-objection-demo/node_modules/knex/types/index"' has no export
ed member 'Raw'.

120   type Raw = RawBuilder | Knex.Raw;
                                   ~~~

node_modules/objection/typings/objection/index.d.ts:525:49 - error TS2694: Namespace '"C:/Users/swapn/IdeaProjects/nest-objection-demo/node_modules/knex/types/index"' has no export
ed member 'JoinClause'.

525     (table: TableRef<QB>, cb: CallbackVoid<Knex.JoinClause>): QB;
                                                    ~~~~~~~~~~

node_modules/objection/typings/objection/index.d.ts:611:22 - error TS2694: Namespace '"C:/Users/swapn/IdeaProjects/nest-objection-demo/node_modules/knex/types/index"' has no export
ed member 'ColumnInfo'.

611     (): Promise<Knex.ColumnInfo>;
                         ~~~~~~~~~~

node_modules/objection/typings/objection/index.d.ts:671:32 - error TS2694: Namespace '"C:/Users/swapn/IdeaProjects/nest-objection-demo/node_modules/knex/types/index"' has no export
ed member 'QueryBuilder'.

671     (this: QB, knexQuery: Knex.QueryBuilder, query: QB): void;
                                   ~~~~~~~~~~~~

node_modules/objection/typings/objection/index.d.ts:1069:45 - error TS2694: Namespace '"C:/Users/swapn/IdeaProjects/nest-objection-demo/node_modules/knex/types/index"' has no expor
ted member 'QueryBuilder'.

1069     toKnexQuery<T = ModelObject<M>>(): Knex.QueryBuilder<T, T[]>;
                                                 ~~~~~~~~~~~~

node_modules/objection/typings/objection/index.d.ts:1190:34 - error TS2694: Namespace '"C:/Users/swapn/IdeaProjects/nest-objection-demo/node_modules/knex/types/index"' has no expor
ted member 'Transaction'.

1190   export type Transaction = Knex.Transaction;
                                      ~~~~~~~~~~~

node_modules/objection/typings/objection/index.d.ts:1191:49 - error TS2709: Cannot use namespace 'Knex' as a type.

1191   export type TransactionOrKnex = Transaction | Knex;
                                                     ~~~~

node_modules/objection/typings/objection/index.d.ts:1385:12 - error TS2709: Cannot use namespace 'Knex' as a type.

1385     knex?: Knex;
                ~~~~

node_modules/objection/typings/objection/index.d.ts:1462:17 - error TS2709: Cannot use namespace 'Knex' as a type.

1462     knex(knex?: Knex): Knex;
                     ~~~~

node_modules/objection/typings/objection/index.d.ts:1462:24 - error TS2709: Cannot use namespace 'Knex' as a type.

1462     knex(knex?: Knex): Knex;
                            ~~~~

node_modules/objection/typings/objection/index.d.ts:1463:23 - error TS2694: Namespace '"C:/Users/swapn/IdeaProjects/nest-objection-demo/node_modules/knex/types/index"' has no expor
ted member 'QueryBuilder'.

1463     knexQuery(): Knex.QueryBuilder;
                           ~~~~~~~~~~~~

node_modules/objection/typings/objection/index.d.ts:1593:24 - error TS2709: Cannot use namespace 'Knex' as a type.

1593     static knex(knex?: Knex): Knex;
                            ~~~~

node_modules/objection/typings/objection/index.d.ts:1593:31 - error TS2709: Cannot use namespace 'Knex' as a type.

1593     static knex(knex?: Knex): Knex;
                                   ~~~~

node_modules/objection/typings/objection/index.d.ts:1594:30 - error TS2694: Namespace '"C:/Users/swapn/IdeaProjects/nest-objection-demo/node_modules/knex/types/index"' has no expor
ted member 'QueryBuilder'.

1594     static knexQuery(): Knex.QueryBuilder;
                                  ~~~~~~~~~~~~

node_modules/objection/typings/objection/index.d.ts:1731:14 - error TS2709: Cannot use namespace 'Knex' as a type.

1731     $knex(): Knex;
                  ~~~~

node_modules/objection/typings/objection/index.d.ts:1732:21 - error TS2709: Cannot use namespace 'Knex' as a type.

1732     $transaction(): Knex;
                         ~~~~

node_modules/objection/typings/objection/index.d.ts:1746:24 - error TS2709: Cannot use namespace 'Knex' as a type.

1746     start(knexOrModel: Knex | AnyModelConstructor): Promise<Transaction>;
                            ~~~~

node_modules/objection/typings/objection/index.d.ts:1824:13 - error TS2709: Cannot use namespace 'Knex' as a type.

1824       knex: Knex,
                 ~~~~

node_modules/objection/typings/objection/index.d.ts:1830:12 - error TS2709: Cannot use namespace 'Knex' as a type.

1830     (knex: Knex, modelClasses: AnyModelConstructor[]): Promise<void>;

```

Am i doing something wrong?

**Comment by willsoto** [comment]
Without looking at your `tsconfig`, what version you upgraded from and stuff like that, I cannot help you. Given that I have been using this library with no issues for months (last release was August 2020) I am inclined to think it's a configuration issue specific to your application. If you can provide a minimal reproduction showing the issue, I will be happy to look into it.

**Comment by swapnil-gawali** [comment]
@willsoto, I hope this [repo ](https://github.com/swapnil-gawali/nest-objection-demo) will make things clear:

https://github.com/swapnil-gawali/nest-objection-demo

**Comment by willsoto** [comment]
Ok this may be related to the `esModuleInterop` flag that I have enabled. You can put `"skipLibCheck": true` in your `tsconfig` to suppress these errors.

**Comment by swapnil-gawali** [comment]
It is working now, but "skipLibCheck" can decrease the integrity of the typing of the application.

**Comment by willsoto** [comment]
Fixed via 728df7629535741af0cb880dadb02049f23c5850. Released in [v5.0.0](https://github.com/willsoto/nestjs-objection/releases/tag/v5.0.0)

**Comment by henrik-d** [comment]
@swapnil-gawali Did v5.0.0 solve the issue for you? I'm still getting these errors in a fresh NestJS project:

```
../node_modules/@willsoto/nestjs-objection/dist/interfaces.d.ts:12:18 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'Config'.
12     config: Knex.Config;

../node_modules/@willsoto/nestjs-objection/dist/interfaces.d.ts:28:34 - error TS2709: Cannot use namespace 'Knex' as a type.
28 export declare type Connection = Knex;

../node_modules/objection/typings/objection/index.d.ts:120:32 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'Raw'.
120   type Raw = RawBuilder | Knex.Raw;

../node_modules/objection/typings/objection/index.d.ts:525:49 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'JoinClause'.
525     (table: TableRef<QB>, cb: CallbackVoid<Knex.JoinClause>): QB;

../node_modules/objection/typings/objection/index.d.ts:611:22 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'ColumnInfo'.
611     (): Promise<Knex.ColumnInfo>;

../node_modules/objection/typings/objection/index.d.ts:671:32 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'QueryBuilder'.
671     (this: QB, knexQuery: Knex.QueryBuilder, query: QB): void;

../node_modules/objection/typings/objection/index.d.ts:1069:45 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'QueryBuilder'.
1069     toKnexQuery<T = ModelObject<M>>(): Knex.QueryBuilder<T, T[]>;

../node_modules/objection/typings/objection/index.d.ts:1190:34 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'Transaction'.
1190   export type Transaction = Knex.Transaction;

../node_modules/objection/typings/objection/index.d.ts:1191:49 - error TS2709: Cannot use namespace 'Knex' as a type.
1191   export type TransactionOrKnex = Transaction | Knex;

../node_modules/objection/typings/objection/index.d.ts:1385:12 - error TS2709: Cannot use namespace 'Knex' as a type.
1385     knex?: Knex;

../node_modules/objection/typings/objection/index.d.ts:1462:17 - error TS2709: Cannot use namespace 'Knex' as a type.
1462     knex(knex?: Knex): Knex;

../node_modules/objection/typings/objection/index.d.ts:1462:24 - error TS2709: Cannot use namespace 'Knex' as a type.
1462     knex(knex?: Knex): Knex;

../node_modules/objection/typings/objection/index.d.ts:1463:23 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'QueryBuilder'.
1463     knexQuery(): Knex.QueryBuilder;

../node_modules/objection/typings/objection/index.d.ts:1593:24 - error TS2709: Cannot use namespace 'Knex' as a type.
1593     static knex(knex?: Knex): Knex;

../node_modules/objection/typings/objection/index.d.ts:1593:31 - error TS2709: Cannot use namespace 'Knex' as a type.
1593     static knex(knex?: Knex): Knex;

../node_modules/objection/typings/objection/index.d.ts:1594:30 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'QueryBuilder'.
1594     static knexQuery(): Knex.QueryBuilder;

../node_modules/objection/typings/objection/index.d.ts:1731:14 - error TS2709: Cannot use namespace 'Knex' as a type.
1731     $knex(): Knex;

../node_modules/objection/typings/objection/index.d.ts:1732:21 - error TS2709: Cannot use namespace 'Knex' as a type.
1732     $transaction(): Knex;

../node_modules/objection/typings/objection/index.d.ts:1746:24 - error TS2709: Cannot use namespace 'Knex' as a type.
1746     start(knexOrModel: Knex | AnyModelConstructor): Promise<Transaction>;

../node_modules/objection/typings/objection/index.d.ts:1824:13 - error TS2709: Cannot use namespace 'Knex' as a type.
1824       knex: Knex,

../node_modules/objection/typings/objection/index.d.ts:1830:12 - error TS2709: Cannot use namespace 'Knex' as a type.
1830     (knex: Knex, modelClasses: AnyModelConstructor[]): Promise<void>;

Found 21 error(s).

```

**Comment by willsoto** [comment]
@henrik-d what version of Knex are you on?

**Comment by henrik-d** [comment]
@willsoto These are my dependencies
```
"@willsoto/nestjs-objection": "^5.0.0",
"knex": "^0.95.1",
"mysql": "^2.18.1",
 "objection": "^2.2.14",
```

**Comment by willsoto** [comment]
Unrelated to this issue: https://github.com/Vincit/objection.js/issues/2012

**Comment by swapnil-gawali** [comment]
> @swapnil-gawali Did v5.0.0 solve the issue for you? I'm still getting these errors in a fresh NestJS project:
> 
> ```
> ../node_modules/@willsoto/nestjs-objection/dist/interfaces.d.ts:12:18 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'Config'.
> 12     config: Knex.Config;
> 
> ../node_modules/@willsoto/nestjs-objection/dist/interfaces.d.ts:28:34 - error TS2709: Cannot use namespace 'Knex' as a type.
> 28 export declare type Connection = Knex;
> 
> ../node_modules/objection/typings/objection/index.d.ts:120:32 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'Raw'.
> 120   type Raw = RawBuilder | Knex.Raw;
> 
> ../node_modules/objection/typings/objection/index.d.ts:525:49 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'JoinClause'.
> 525     (table: TableRef<QB>, cb: CallbackVoid<Knex.JoinClause>): QB;
> 
> ../node_modules/objection/typings/objection/index.d.ts:611:22 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'ColumnInfo'.
> 611     (): Promise<Knex.ColumnInfo>;
> 
> ../node_modules/objection/typings/objection/index.d.ts:671:32 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'QueryBuilder'.
> 671     (this: QB, knexQuery: Knex.QueryBuilder, query: QB): void;
> 
> ../node_modules/objection/typings/objection/index.d.ts:1069:45 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'QueryBuilder'.
> 1069     toKnexQuery<T = ModelObject<M>>(): Knex.QueryBuilder<T, T[]>;
> 
> ../node_modules/objection/typings/objection/index.d.ts:1190:34 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'Transaction'.
> 1190   export type Transaction = Knex.Transaction;
> 
> ../node_modules/objection/typings/objection/index.d.ts:1191:49 - error TS2709: Cannot use namespace 'Knex' as a type.
> 1191   export type TransactionOrKnex = Transaction | Knex;
> 
> ../node_modules/objection/typings/objection/index.d.ts:1385:12 - error TS2709: Cannot use namespace 'Knex' as a type.
> 1385     knex?: Knex;
> 
> ../node_modules/objection/typings/objection/index.d.ts:1462:17 - error TS2709: Cannot use namespace 'Knex' as a type.
> 1462     knex(knex?: Knex): Knex;
> 
> ../node_modules/objection/typings/objection/index.d.ts:1462:24 - error TS2709: Cannot use namespace 'Knex' as a type.
> 1462     knex(knex?: Knex): Knex;
> 
> ../node_modules/objection/typings/objection/index.d.ts:1463:23 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'QueryBuilder'.
> 1463     knexQuery(): Knex.QueryBuilder;
> 
> ../node_modules/objection/typings/objection/index.d.ts:1593:24 - error TS2709: Cannot use namespace 'Knex' as a type.
> 1593     static knex(knex?: Knex): Knex;
> 
> ../node_modules/objection/typings/objection/index.d.ts:1593:31 - error TS2709: Cannot use namespace 'Knex' as a type.
> 1593     static knex(knex?: Knex): Knex;
> 
> ../node_modules/objection/typings/objection/index.d.ts:1594:30 - error TS2694: Namespace '"/Users/me/Projekte/my_project/node_modules/knex/types/index"' has no exported member 'QueryBuilder'.
> 1594     static knexQuery(): Knex.QueryBuilder;
> 
> ../node_modules/objection/typings/objection/index.d.ts:1731:14 - error TS2709: Cannot use namespace 'Knex' as a type.
> 1731     $knex(): Knex;
> 
> ../node_modules/objection/typings/objection/index.d.ts:1732:21 - error TS2709: Cannot use namespace 'Knex' as a type.
> 1732     $transaction(): Knex;
> 
> ../node_modules/objection/typings/objection/index.d.ts:1746:24 - error TS2709: Cannot use namespace 'Knex' as a type.
> 1746     start(knexOrModel: Knex | AnyModelConstructor): Promise<Transaction>;
> 
> ../node_modules/objection/typings/objection/index.d.ts:1824:13 - error TS2709: Cannot use namespace 'Knex' as a type.
> 1824       knex: Knex,
> 
> ../node_modules/objection/typings/objection/index.d.ts:1830:12 - error TS2709: Cannot use namespace 'Knex' as a type.
> 1830     (knex: Knex, modelClasses: AnyModelConstructor[]): Promise<void>;
> 
> Found 21 error(s).
> 
> ```

i didn't check on the latest version
